services:
  # MySQL Database for Development
  mysql-dev:
    image: mysql:8.0
    container_name: bible-daily-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${DB_DATABASE:-bible_daily_dev}
      MYSQL_USER: ${DB_USERNAME:-bible_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-bible_password}
    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./backend/database/init:/docker-entrypoint-initdb.d
    networks:
      - bible-daily-dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=256M
      --innodb-log-file-size=64M

  # Redis for Development
  redis-dev:
    image: redis:7-alpine
    container_name: bible-daily-redis-dev
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_dev_data:/data
      - ./dev-config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - bible-daily-dev-network
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5

  # Adminer for Database Management (optional)
  adminer:
    image: adminer:latest
    container_name: bible-daily-adminer-dev
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    networks:
      - bible-daily-dev-network
    depends_on:
      mysql-dev:
        condition: service_healthy
    profiles:
      - tools

  # Redis Commander for Redis Management (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: bible-daily-redis-commander-dev
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis-dev:6379
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    networks:
      - bible-daily-dev-network
    depends_on:
      redis-dev:
        condition: service_healthy
    profiles:
      - tools

volumes:
  mysql_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  bible-daily-dev-network:
    driver: bridge
